### ISSUE TITLE
support expr 

### ISSUE THREAD

**Issue by liyongjing** [andrewpillar/query#2]
I want add basic expr such as  NotEq, NotLike,Lt,LtOrEq,Gt, GtOrEq etc
one api definition such as

```
func WhereLike(col string, val interface{}) Option{}
func WhereEq(col string, val interface{}) Option {}
func WhereNotEq(col string, val interface{}) Option {}
```

one api defintion such as 
```
const (
	OpEq   = "="
	OpGt   = ">"
	OpGtOrEq = ">="
	OpLt   = "<"
	OpLike = "LIKE"
)
func Where(col string, op string, val interface{}) Option {}
```
which?

**Comment by andrewpillar** [comment]
> const (
> 	OpEq   = "="
> 	OpGt   = ">"
> 	OpGtOrEq = ">="
> 	OpLt   = "<"
> 	OpLike = "LIKE"
> )
> func Where(col string, op string, val interface{}) Option {}
How would this work for WHERE clauses that use "IN"?

**Comment by liyongjing** [comment]
Which is better for public api defintion? internal implement separately with basic operators and complexity operators.

**Comment by andrewpillar** [comment]
> Which is better for public api defintion?
How about implement the new API, but keep the old public API just as a
wrapper around the new one. Something like this:

```
type Op string

const (
    OpEq Op = "="
)

func Where(col string, op Op, val interface{}) Option {}

func WhereEq(col string, val interface{}) Option {
    return Where(col, OpEq, val)
}
```

Also, how about making the `op` passed to the `Where` function its own
type? I prefer the explicitness that comes with this.

We could also add another function called `WhereRaw` for handling
values for the query we don't want to use bindvars for.

```
func WhereRaw(col string, op Op, val interface{}) Option {}
```
