### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by DingdingZhou** [andrewpillar/query#4]
i want to translate your post 
"https://andrewpillar.com/programming/2019/07/13/orms-and-query-building-in-go/ "
to simple chinese; 
can I do that??

**Comment by andrewpillar** [comment]
> i want to translate your post
> "
> https://andrewpillar.com/programming/2019/07/13/orms-and-query-building-in-go/
> "
Sure, where do you intend on hosting it?

**Comment by DingdingZhou** [comment]
> i want to translate your post " https://andrewpillar.com/programming/2019/07/13/orms-and-query-building-in-go/ "
> Sure, where do you intend on hosting it?

i want to post it  in this repos:
https://github.com/studygolang/gctt 

And I have committed a pull request:
https://github.com/studygolang/GCTT/pull/1343/commits/8586505a218ae72ded0a753e007a8cbd5fed92dd

**Comment by andrewpillar** [comment]
Alright, thanks for letting me know, this looks good.

**Comment by DingdingZhou** [comment]
I happen to use Go to implement a simple general query for Sqlite some days ago，but it‘s ugly really. And your post helps me a lot； very thank you
